# Generated by Django 4.1.6 on 2023-02-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_dob_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
