# Generated by Django 4.1.6 on 2023-02-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_hospital_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
    ]
