# Generated by Django 3.2.17 on 2023-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230212_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('quality', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.ManyToManyField(blank=True, to='home.UploadedFile'),
        ),
    ]
