# Generated by Django 3.2.17 on 2023-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230212_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='ocr',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
