# Generated by Django 3.2.17 on 2023-02-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uploadedfile_ocr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='quality',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
